on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: 36 8 * * *

name: Semgrep

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        id: semgrep
        run: |
          semgrep --config=semgrep-rules.yml --sarif-file=semgrep-results.sarif || exit 1
          
      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep-results.sarif

      - name: Fail the pipeline if Semgrep found issues
        if: ${{ failure() }}
        run: |
          echo "Semgrep found issues, failing the pipeline."
          exit 1
